Django_Backend_assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
import movies_collection.views
from accounts.views import get_request_count, reset_request_count
from rest_framework_simplejwt import views as jwt_views
from blog.views import PostListView, PermissionTestingView
from django.contrib.auth import views as auth_views
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

router_v1 = routers.DefaultRouter()
router_v1.register(r"movies", movies_collection.views.MovieViewSet)
router_v1.register(r"collection", movies_collection.views.CollectionViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('collections/', include('movies_collection.urls')),
    path("api/v1/", include(router_v1.urls), name="api-root"),
    # path('request-count/', get_request_count),
    path('request-count/', get_request_count, name='get_request_count'),
    path('request-count/reset/', reset_request_count, name='reset_request_count'),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('posts/', PostListView.as_view(), name='post-list'),
    path('perm_testing_view/', PermissionTestingView.as_view(), name='permission-testing-view'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc')
]

accounts/urls.py
# urls.py
from django.urls import path
from .views import RegistrationView

urlpatterns = [
    path('register/', RegistrationView.as_view(), name='register'),
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=400)
    body = models.TextField()
    is_published = models.BooleanField(default=False)
    class Meta:
        permissions = [
            (
                "set_published_status",
                "Can set the status of the post to either publish or not"
            )
        ]
        
        # ref : https://testdriven.io/blog/django-permissions/
        # ref : https://testdriven.io/blog/django-permissions/

movies_collection/models.py
from django.db import models
from uuid import uuid4


class Movie(models.Model):
    title = models.CharField(max_length=100, null=False)
    description = models.TextField()
    genres = models.CharField(max_length=250)
    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)

class Collection(models.Model):
    title = models.CharField(max_length=100, null=False)
    description = models.TextField()
    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    movies = models.ManyToManyField(
        Movie,
        related_name="collections",
        through="MovieCollection",
        through_fields=("collection", "movie"),
    )

class MovieCollection(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

blog/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import ListView

from blog.models import Post
from django.views import View
from rest_framework.views  import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import BasicAuthentication
# class PostListView(PermissionRequiredMixin, ListView):
#     permission_required = "blog.view_post"
#     template_name = "blog/post_list.html"
#     model = Post
    
class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    
# ref : https://testdriven.io/blog/django-permissions/
# ref : https://testdriven.io/blog/django-permissions/

class PermissionTestingView(APIView):
    permission_classes = [IsAuthenticated]
    authentication_classes = [BasicAuthentication]
    def get(self, request):
        print("request.user::::::::::",request.user)
        if not request.user.has_perm("blog.set_published_status"):
            return Response({"error":"You don't have permission to access it"})
        return Response({"Success":"API is working fine. Welcome...."})
        

blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Beautiful Navbar Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    {% comment %} Ref : https://testdriven.io/blog/django-permissions/ {% endcomment %}
    {% comment %} Ref : https://testdriven.io/blog/django-permissions/ {% endcomment %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <!-- Nav item visible only if the user has permission for 'view_post' -->
                {% if perms.blog.view_post %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post-list' %}">Post</a>
                    </li>
                {% endif %}
                <!-- Nav item visible only if the user has permission for 'view_user' -->
                {% if perms.movies_collection.view_movie %}
                    <li class="nav-item">
                        <a class="nav-link" >Movie</a>
                    </li>
                {% endif %}
                {% if perms.movies_collection.view_collection %}
                    <li class="nav-item">
                        <a class="nav-link" >Collection</a>
                    </li>
                {% endif %}
                {% if perms.movies_collection.view_moviecollection %}
                    <li class="nav-item">
                        <a class="nav-link" >MovieCollection</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" >{{request.user}}</a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">logout</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <!-- Content here -->
        <h1>Welcome to the Beautiful Navbar Example</h1>
        <p>This is an example of a responsive navbar using Bootstrap that displays different links based on user permissions.</p>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>